version: 2
builds:
- env:
  - CGO_ENABLED=1
  - CC=gcc
  goos:
  - linux
  # Authduck depends on sqlite, which require CGO. however cross-compiling cgo
  # is hard. thus to keep things simple, for now we will only support linux-amd64.
  # ref:
  # - https://goreleaser.com/cookbooks/cgo-and-crosscompiling/
  # - https://www.bytebase.com/blog/how-to-cross-compile-with-cgo-use-goreleaser-and-github-action/
  #- windows
  #- darwin
  goarch:
  - amd64
  #- arm64

dockers:
- image_templates: ["ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: docker/release.Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/azophy/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/azophy/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
#- image_templates: ["ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
#  goarch: arm64
#  dockerfile: docker/release.Dockerfile
#  use: buildx
#  build_flag_templates:
#  - --platform=linux/arm64/v8
#  - --label=org.opencontainers.image.title={{ .ProjectName }}
#  - --label=org.opencontainers.image.description={{ .ProjectName }}
#  - --label=org.opencontainers.image.url=https://github.com/azophy/{{ .ProjectName }}
#  - --label=org.opencontainers.image.source=https://github.com/azophy/{{ .ProjectName }}
#  - --label=org.opencontainers.image.version={{ .Version }}
#  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#  - --label=org.opencontainers.image.revision={{ .FullCommit }}
#  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-amd64
  #- ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/azophy/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-amd64
  #- ghcr.io/azophy/{{ .ProjectName }}:{{ .Version }}-arm64v8

