# fly.toml app configuration file generated for authduck on 2024-08-11T11:01:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'authduck'
primary_region = 'sin'

[build]
  image = "ghcr.io/azophy/authduck:latest"

[env]
  APP_PORT = '3000'
  BASE_URL = "https://authduck.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
